### ISSUE TITLE
**TF2.1-GPU 运行YoutubeDNN的电影数据集DEMO始出现了bug**

### ISSUE THREAD

**Issue by wp931120** [shenweichen/DeepMatch#11]
**运行YoutubeDNN的电影数据集DEMO始出现了bug**

**Operating environment(运行环境):**
 - python version [3.6]
 - tensorflow version [2.1 - GPU]
 - deepmatch version [0.1.2]

 运行到这句话时
 item_embs = item_embedding_model.predict(all_item_model_input, batch_size=2 ** 12)
出现如下bug (查了一下，可能是TF2.0 + 的eager模式导致的 ):

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
D:\Users\wangpeng.BEVOL\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\eager\execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     60                                                op_name, inputs, attrs,
---> 61                                                num_outputs)
     62   except core._NotOkStatusException as e:

TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: pooling_layer/Identity:0

During handling of the above exception, another exception occurred:

_SymbolicException                        Traceback (most recent call last)
<ipython-input-25-9389f4b6a968> in <module>
----> 1 item_embs = item_embedding_model.predict(all_item_model_input, batch_size=2)

D:\Users\wangpeng.BEVOL\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\keras\engine\training.py in predict(self, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing)
   1011         max_queue_size=max_queue_size,
   1012         workers=workers,
-> 1013         use_multiprocessing=use_multiprocessing)
   1014 
   1015   def reset_metrics(self):

D:\Users\wangpeng.BEVOL\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in predict(self, model, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing, **kwargs)
    496         model, ModeKeys.PREDICT, x=x, batch_size=batch_size, verbose=verbose,
    497         steps=steps, callbacks=callbacks, max_queue_size=max_queue_size,
--> 498         workers=workers, use_multiprocessing=use_multiprocessing, **kwargs)
    499 
    500 

D:\Users\wangpeng.BEVOL\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in _model_iteration(self, model, mode, x, y, batch_size, verbose, sample_weight, steps, callbacks, max_queue_size, workers, use_multiprocessing, **kwargs)
    473               mode=mode,
    474               training_context=training_context,
--> 475               total_epochs=1)
    476           cbks.make_logs(model, epoch_logs, result, mode)
    477 

D:\Users\wangpeng.BEVOL\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in run_one_epoch(model, iterator, execution_function, dataset_size, batch_size, strategy, steps_per_epoch, num_samples, mode, training_context, total_epochs)
    126         step=step, mode=mode, size=current_batch_size) as batch_logs:
    127       try:
--> 128         batch_outs = execution_function(iterator)
    129       except (StopIteration, errors.OutOfRangeError):
    130         # TODO(kaftan): File bug about tf function and errors.OutOfRangeError?

D:\Users\wangpeng.BEVOL\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py in execution_function(input_fn)
     96     # `numpy` translates Tensors to values in Eager mode.
     97     return nest.map_structure(_non_none_constant_value,
---> 98                               distributed_function(input_fn))
     99 
    100   return execution_function

D:\Users\wangpeng.BEVOL\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\eager\def_function.py in __call__(self, *args, **kwds)
    566         xla_context.Exit()
    567     else:
--> 568       result = self._call(*args, **kwds)
    569 
    570     if tracing_count == self._get_tracing_count():

D:\Users\wangpeng.BEVOL\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\eager\def_function.py in _call(self, *args, **kwds)
    604       # In this case we have not created variables on the first call. So we can
    605       # run the first trace but we should fail if variables are created.
--> 606       results = self._stateful_fn(*args, **kwds)
    607       if self._created_variables:
    608         raise ValueError("Creating variables on a non-first call to a function"

D:\Users\wangpeng.BEVOL\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\eager\function.py in __call__(self, *args, **kwargs)
   2361     with self._lock:
   2362       graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
-> 2363     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
   2364 
   2365   @property

D:\Users\wangpeng.BEVOL\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\eager\function.py in _filtered_call(self, args, kwargs)
   1609          if isinstance(t, (ops.Tensor,
   1610                            resource_variable_ops.BaseResourceVariable))),
-> 1611         self.captured_inputs)
   1612 
   1613   def _call_flat(self, args, captured_inputs, cancellation_manager=None):

D:\Users\wangpeng.BEVOL\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\eager\function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1690       # No tape is watching; skip to running the function.
   1691       return self._build_call_outputs(self._inference_function.call(
-> 1692           ctx, args, cancellation_manager=cancellation_manager))
   1693     forward_backward = self._select_forward_and_backward_functions(
   1694         args,

D:\Users\wangpeng.BEVOL\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\eager\function.py in call(self, ctx, args, cancellation_manager)
    543               inputs=args,
    544               attrs=("executor_type", executor_type, "config_proto", config),
--> 545               ctx=ctx)
    546         else:
    547           outputs = execute.execute_with_cancellation(

D:\Users\wangpeng.BEVOL\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\eager\execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     73       raise core._SymbolicException(
     74           "Inputs to eager execution function cannot be Keras symbolic "
---> 75           "tensors, but found {}".format(keras_symbolic_tensors))
     76     raise e
     77   # pylint: enable=protected-access

_SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, but found [<tf.Tensor 'pooling_layer/Identity:0' shape=(3707, 32) dtype=float32>]

**Comment by shenweichen** [comment]
嗯 egaer模式可能有些问题，这个我们后续会进行优化。可以先尝试1.14等版本

**Comment by wuwenjie1992** [comment]
同，可以临时关闭一下egaer模式

```python
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
```

**Comment by DenceChen** [comment]
tf2.0以上的版本关闭下egaer模式就好了

**Comment by Tang-08080103** [comment]
> ```python
> import tensorflow as tf
> tf.compat.v1.disable_eager_execution()
> 关闭之后仍然出现新的问题？

**Comment by Tang-08080103** [comment]
在程序最开始的位置加解决了这个问题，之前我加在后面导致错误！
