### ISSUE TITLE
DeepMatch/example/preprocess.py里面的gen_data_set函数有bug

### ISSUE THREAD

**Issue by JyiHUO** [shenweichen/DeepMatch#14]
**Describe the bug(问题描述)**
这行[代码](https://github.com/shenweichen/DeepMatch/blob/c376af36e6cad1ffc5167085cc1bd81cf5ca76b3/examples/preprocess.py#L23)以及下面出现hist[::-1]的代码，都不需要翻转，因为下面的这行代码执行之后：

`data.sort_values("timestamp", inplace=True)`

用户的行为已经根据时间从小到大排序了，如果在翻转hist[::-1]，就会导致下面函数gen_model_input里面的变量train_seq_pad的数据出现大量重复：

![image](https://user-images.githubusercontent.com/16526817/79357379-da436480-7f37-11ea-8b62-f7477d6c16e3.png)

![image](https://user-images.githubusercontent.com/16526817/79357445-f0e9bb80-7f37-11ea-9f92-359d1ce87e4b.png)

这几个样本都是完全一样的，是不可能发生的。

**To Reproduce(复现步骤)**
1. Go to 'DeepMatch/example/'
2. Click on 'python run_dssm_negsampling.py'

**Operating environment(运行环境):**
 - python version [e.g. 3.4, 3.6]
 - tensorflow version [e.g. 1.4.0, 1.12.0]
 - deepmatch version [e.g. 0.1.1,]

**Additional context**

**Comment by mh233** [comment]
我也想问这个问题，既然gen_data_set里面把train_seq反转了，那为什么gen_model_input里面对其使用pad_sequences函数进行填充时，不加上参数truncating='post'让长度>50的seq截掉后面的的数据？造成长度>50的seq全部是一样的序列

**Comment by JyiHUO** [comment]
如果不翻转的话，是可以这样写的

**Comment by mh233** [comment]
> 如果不翻转的话，是可以这样写的

应该是前面[::-1]翻转的话，后面加参数是正确？所以这个地方是bug对吧--->去掉[::-1]翻转 或 加参数truncating='post'

**Comment by JyiHUO** [comment]
如果truncating='post'是取序列的前部分数据，比如说前50个，那么翻转就是合法的。

**Comment by shenweichen** [comment]
已经修复了，感谢！
