### ISSUE TITLE
mind example error

### ISSUE THREAD

**Issue by Diamond0728** [shenweichen/DeepMatch#17]
**Describe the question(问题描述)**
您好，我在youtubeDNN的example里面看到了可以使用MIND模型的代码
https://github.com/shenweichen/DeepMatch/blob/6d8209820dcf576dbca8eed9ca76d9012b1868de/examples/run_youtubednn_sampledsoftmax.py#L79
当我把这一行去掉注释，并且删除后面的`if MIND`，还是会python语法错误
我想请问这一步的目的是什么，这样可以以便于我在自己的代码中将其修正，谢谢。

**Operating environment(运行环境):**
 - python version [3.7.6]
 - tensorflow version [ 1.14.0,]
 - deepmatch version [ 0.1.2,]

**Comment by shenweichen** [comment]
`MIND`模型会产生`k_max`的用户兴趣向量，通过`user_embs = user_embs[:, i, :]`取到用户第`i`个用户兴趣向量，其中`i in [0,k_max)`。
所以你应该在去掉注释后删除 `i in [0,k_max) if MIND `这部分内容。
另外可以添加小助手微信**deepctrbot** 加入DeepMatch交流群。

**Comment by Diamond0728** [comment]
谢谢您的解答
