### ISSUE TITLE
deepmatch 中的sdm中的process中是否写反了～

### ISSUE THREAD

**Issue by Aleczhang13** [shenweichen/DeepMatch#27]
example中的  prefer_sess_length和short_sess_length是否写反了呢～
train_model_input = {"user_id": train_uid, "movie_id": train_iid, "short_movie_id": train_short_item_pad,
        "prefer_movie_id": train_prefer_item_pad, "prefer_sess_length": train_short_len, "short_sess_length":
        train_prefer_len, 'short_genres': train_short_genres_pad, 'prefer_genres': train_prefer_genres_pad}

**Comment by shenweichen** [comment]
已修复，感谢！
