### ISSUE TITLE
import提示没有preprocess

### ISSUE THREAD

**Issue by drxmy** [shenweichen/DeepMatch#31]
**Describe the question(问题描述)**
在运行YoutubeDNN with sampled softmax这个例子时，import提示没有preprocess。我也没有查到这个库。是我版本安装的不对吗？感谢回答

**Operating environment(运行环境):**
 - python version 3.7
 - tensorflow version 2.2
 - deepmatch version0.13

**Comment by shenweichen** [comment]
这个文件在仓库中的examples目录下

**Comment by drxmy** [comment]
非常感谢！
