### ISSUE TITLE
DSSM最后一步没有看懂

### ISSUE THREAD

**Issue by Ethan199111** [shenweichen/DeepMatch#33]
你好，关于DSSM最后一步我有一些疑问

DSSM最后我看是求了user output和item output的余弦距离，然后又进行了sigmoid最后求交叉熵，余弦距离会把得分限制在-1至1之间，这样再进行sigmoid并求交叉熵非常奇怪啊。

我觉得应该求内积后直接使用sigmoid_cross_entropy来得到loss function

我们自己的实践证明上述方法也是有效的，烦请作者说一些这里的思路。

**Comment by shenweichen** [comment]
这里是仿照DSSM论文进行的实现，使用了cos相似度，代码中也提供了参数可以使用内积，具体的请查阅文档
