### ISSUE TITLE
SDM预处理代码有误

### ISSUE THREAD

**Issue by vikotse** [shenweichen/DeepMatch#38]
**Describe the bug(问题描述)**
SDM预处理代码有误

**To Reproduce(复现步骤)**
DeepMatch/examples/preprocess.py 107~108行
`"prefer_sess_length": train_short_len, "short_sess_length": train_prefer_len`
请问这两个字段的值是写反了？short及prefer的序列长度

**Operating environment(运行环境):**
 - python version [e.g. 3.4, 3.6]
 - tensorflow version [e.g. 1.4.0, 1.12.0]
 - deepmatch version [e.g. 0.1.1,]

**Additional context**

**Comment by shenweichen** [comment]
已更正
