### ISSUE TITLE
run_youtubednn 保存模型失败

### ISSUE THREAD

**Issue by fangjiong** [shenweichen/DeepMatch#42]
**Describe the bug(问题描述)**
尝试使用model.save的方式去保存youtbednn模型报错

**To Reproduce(复现步骤)**
在history这一行后面新增保存模型的两行代码
    history = model.fit(train_model_input, train_label,  # train_label,
                        batch_size=256, epochs=20, verbose=1, validation_split=0.0, )

    model_path = './my_model'
    model.save(model_path)
    
    # 4. Generate user features for testing and full item features for retrieval
    test_user_model_input = test_model_input
    all_item_model_input = {"movie_id": item_profile['movie_id'].values}

**Operating environment(运行环境):**
 - python version 3.7.3
 - tensorflow version 2.2.0
 - deepmatch version 0.2.0

**Comment by zanshuxun** [comment]
报的什么错？
