### ISSUE TITLE
run_youtubednn模型保存后重新读取报错 Unknown layer: EmbeddingIndex

### ISSUE THREAD

**Issue by fangjiong** [shenweichen/DeepMatch#43]
**Describe the bug(问题描述)**
run_youtubednn模型保存后重新读取报错 Unknown layer: EmbeddingIndex

**To Reproduce(复现步骤)**
    history = model.fit(train_model_input, train_label,  # train_label,
                        batch_size=256, epochs=20, verbose=1, validation_split=0.0, )

    model_path = './my_model'
    model.save(model_path)
    new_model = tf.keras.models.load_model(model_path)

 - python version 3.7
 - tensorflow version  1.15.0
 - deepmatch version 0.2.0

**Additional context**

**Comment by zanshuxun** [comment]
请参考文档中加载模型的代码
https://deepmatch.readthedocs.io/en/latest/FAQ.html#save-or-load-weights-models

**Comment by sxzhou1937** [comment]
> 请参考文档中加载模型的代码 https://deepmatch.readthedocs.io/en/latest/FAQ.html#save-or-load-weights-models

@zanshuxun 这个连接的保存方式都是h5的 我如果想保存整个结构，如`save_model(model, ',/model', 'tf')`就会报错
```
ValueError: Unable to save the object ListWrapper([<tensorflow.python.keras.layers.core.Activation object at 0x0000025C163F08D0>, <tensorflow.python.keras.layers.core.Activation object at 0x0000025C163F0668>]) (a list wrapper constructed to track trackable TensorFlow objects). A list element was replaced (__setitem__, __setslice__), deleted (__delitem__, __delslice__), or moved (sort). In order to support restoration on object creation, tracking is exclusively for append-only data structures.

If you don't need this list checkpointed, wrap it in a non-trackable object; it will be subsequently ignored.
```

**Comment by saskiabosma** [comment]
Hi [sxzhou1937](https://github.com/sxzhou1937) ! I had the same problem and the fix mentionned there worked for me: [https://github.com/shenweichen/DeepCTR/issues/344](https://github.com/shenweichen/DeepCTR/issues/344)
