### ISSUE TITLE
Mind中动态路由的routing logists问题

### ISSUE THREAD

**Issue by duyiqi17** [shenweichen/DeepMatch#44]
https://github.com/shenweichen/DeepMatch/blob/6b059caa0ae2ae419a96854871ba816691b30d5d/deepmatch/layers/core.py#L175
如题，胶囊中的routing logists是一个全局的参数吗？看论文貌似是在routing process之前随机初始化的。

**Comment by zanshuxun** [comment]
1、这个也不是全局的参数吧 是这个Layer的可训练参数 
2、按照代码 这里的self.routing_logits就是在routing process之前随机初始化的吧

**Comment by 940711227** [comment]
感觉这里把routing_logits当成variable是有问题的，相当于每个batch都保留了之前的参数，按照论文的意思应该实现成constant吧，每个batch来的时候都重新聚类

**Comment by shenweichen** [comment]
很抱歉，这个问题一直没来得及看，我们后面会抽空看一下。也欢迎大家来贡献代码帮助改进和优化。

**Comment by cookie54sun** [comment]
请问delta_routing_logits是不是不应该做reduce_sum操作，这样一个batch内的所有样本的delta_routing_logits都变得一样了
