### ISSUE TITLE
Mind test failed

### ISSUE THREAD

**Issue by Hizeal** [shenweichen/DeepMatch#55]
**Describe the question(问题描述)**

运行MIND模型，第5步 （寻找ANN以及预估结果）无法运行。

运行到这一步时`D, I = index.search(np.ascontiguousarray(user_embs), 50)`，出现  `too many values to unpack(expected 2)`

![image](https://user-images.githubusercontent.com/63534873/121283594-fbba9900-c90d-11eb-9cb1-0aee590598e7.png)

**Operating environment(运行环境):**

 - python version `3.6.2`
 - tensorflow version `tensorflow-gpu==1.14.0`
 - deepmatch version  `0.2.0`,

**Comment by Zoeson** [comment]
维度不匹配：
mind得到的user_embs是3维的：N*k_max*dim, N是user的个数，k_max是一个user通过mind用几个向量表示，dim向量的维度
index.search(user_embs)了的user_embs要求是2维， N*dim,

**Comment by shenweichen** [comment]
仔细看下例子
    # user_embs = user_embs[:, i, :]  # i in [0,k_max) if MIND
