### ISSUE TITLE
召回率偏低，使用DSSM模型，在用faiss检索的时候召回率偏低，只有recall@100只有0.2左右，有无什么优化的方案呢？

### ISSUE THREAD

**Issue by Bradyzzhang** [shenweichen/DeepMatch#62]
Please refer to the [FAQ](https://deepmatch.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepMatch/issues) before you ask the question.

**Describe the question(问题描述)**
A clear and concise description of what the question is.

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.4.0,]
 - deepmatch version [e.g. 0.2.0,]

**Comment by Beytab** [comment]
我这边dssm训练loss不下降，基本维持不变，所以结果很差，不止到楼主是否一样

**Comment by Bradyzzhang** [comment]
是的 一模一样
加入负采样好像会下降

**Comment by Bradyzzhang** [comment]
请问下你的recall@k大概是多少呢

**Comment by Beytab** [comment]
0.008到0.049，我这边用adam会高一些，tf1.x 的adagrad能调的不多；你这边负采样的比例是好多嘞

**Comment by Bradyzzhang** [comment]
neg：3？ ***@***.******@***.***差不多0.01。

**Comment by sherpahu** [comment]
请问解决了吗?我也碰到了一样的问题

**Comment by Bradyzzhang** [comment]
你可以将模型的user和item的hidden units调成64，32试试，会有一些提升

**Comment by sherpahu** [comment]
> 你可以将模型的user和item的hidden units调成64，32试试，会有一些提升
> […](#)
> Sent from my iPhone
> On Jan 16, 2022, at 9:19 PM, sherpahu ***@***.***> wrote: ﻿ 请问解决了吗?我也碰到了一样的问题 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.

我发现loss还是一样不下降, 虽然recall涨了一点点  
我的ipynb[https://sherpahu.lanzouj.com/iffWNyvxlnc](https://sherpahu.lanzouj.com/iffWNyvxlnc)

**Comment by Bradyzzhang** [comment]
loss不下降的话可以把dssm的相似度函数加入温度系数gamma=10

**Comment by sherpahu** [comment]
> loss不下降的话可以把dssm的相似度函数加入温度系数gamma=10
> […](#)
> Sent from my iPhone
> On Jan 17, 2022, at 11:18 AM, sherpahu ***@***.***> wrote: ﻿ 你可以将模型的user和item的hidden units调成64，32试试，会有一些提升 … Sent from my iPhone On Jan 16, 2022, at 9:19 PM, sherpahu @.***> wrote: ﻿ 请问解决了吗?我也碰到了一样的问题 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread. 我发现loss还是一样不下降, 虽然recall涨了一点点 我的ipynbhttps://sherpahu.lanzouj.com/iffWNyvxlnc — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.

感谢大佬  
我调了调gamma，再调了一下损失函数和l2_reg，终于把recall提到了20%以上了

**Comment by Bradyzzhang** [comment]
请问你l2和损失函数具体怎么调整的呢？我也想优化下

**Comment by sherpahu** [comment]
https://gist.github.com/sherpahu/029982cb32560f61c470bd3977469265  
DSSM的gamma=10是在deepmatch的package里面直接加的

**Comment by shenweichen** [comment]
请更新deepmatch 最新的v0.3 版本，并使用softmax损失 recall@50 ～35%
使用例子：
https://github.com/shenweichen/DeepMatch/blob/master/examples/colab_MovieLen1M_DSSM_InBatchSoftmax.ipynb

**Comment by lowenhu** [comment]
> loss不下降的话可以把dssm的相似度函数加入温度系数gamma=10
> […](#)
> Sent from my iPhone
> On Jan 17, 2022, at 11:18 AM, sherpahu ***@***.***> wrote: ﻿ 你可以将模型的user和item的hidden units调成64，32试试，会有一些提升 … Sent from my iPhone On Jan 16, 2022, at 9:19 PM, sherpahu @.***> wrote: ﻿ 请问解决了吗?我也碰到了一样的问题 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread. 我发现loss还是一样不下降, 虽然recall涨了一点点 我的ipynbhttps://sherpahu.lanzouj.com/iffWNyvxlnc — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.

大佬，求一个加入温度系数gamma=10的代码

**Comment by lowenhu** [comment]
> https://gist.github.com/sherpahu/029982cb32560f61c470bd3977469265 DSSM的gamma=10是在deepmatch的package里面直接加的 环境是Tensorflow-gpu==1.15 原本的损失函数是sampledsoftmaxloss，在DSSM这里效果非常非常差，我调了很多回都是在第二个epoch之后就loss不下降或者过拟合loss为1e-5数量级。换成binary_crossentropy之后效果好多了

想知道，如何加入温度系数gamma=10，求一个代码
