### ISSUE TITLE
preprocess数据集处理

### ISSUE THREAD

**Issue by Bradyzzhang** [shenweichen/DeepMatch#65]
Please refer to the [FAQ](https://deepmatch.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepMatch/issues) before you ask the question.

**Describe the question(问题描述)**
A clear and concise description of what the question is.

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.4.0,]
 - deepmatch version [e.g. 0.2.0,]
请问下，数据集处理为什么没有用到rating特征，而且也没有用到其他item特征：例如genres，title等，有没有办法加入？
![image](https://user-images.githubusercontent.com/95210397/145529877-f73a4db7-19a0-4a39-9f45-681901443ed2.png)

**Comment by bbruceyuan** [comment]
完全是可以加入的。比如 item 只要你构造一个类似的 item_profile 然后把相应的特征在构造样本的时候加入进行就OK了。

作者之所以没有这么做应该是有两个方面的考量：
1. youtubednn item 侧只需要有 movie_id 特征就OK了，为了和 fm/dssm 够用一个 run_example, 所以没有加入相关特征
2. 为了代码更简洁，反正这只是一个测试的demo。所以你想加item侧特征是OK的，比如item的平均分数。
