### ISSUE TITLE
from preprocess import gen_data_set, gen_model_input

### ISSUE THREAD

**Issue by zilinly** [shenweichen/DeepMatch#71]
Please refer to the [FAQ](https://deepmatch.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepMatch/issues) before you ask the question.

**Describe the question(问题描述)**
A clear and concise description of what the question is.

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.4.0,]
 - deepmatch version [e.g. 0.2.0,]

**Comment by zilinly** [comment]
所以是从哪里导入preprocess 模块

**Comment by gotid** [comment]
https://github.com/shenweichen/DeepMatch/blob/master/examples/preprocess.py
