### ISSUE TITLE
官方示例YoutubeDNN无法运行

### ISSUE THREAD

**Issue by xqk** [shenweichen/DeepMatch#72]
/home/user/anaconda3/envs/paddle/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:437: UserWarning: `tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
  warnings.warn('`tf.keras.backend.set_learning_phase` is deprecated and '
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_1423/2555372007.py in <module>
      1 K.set_learning_phase(True)
----> 2 model = YoutubeDNN(user_feature_columns, item_feature_columns, num_sampled=5, user_dnn_hidden_units=(64, embedding_dim))
      3 # model = MIND(user_feature_columns,item_feature_columns,dynamic_k=False,p=1,k_max=2,num_sampled=5,user_dnn_hidden_units=(64,embedding_dim),init_std=0.001)
      4 
      5 model.compile(optimizer="adam", loss=sampledsoftmaxloss) # binary_crossentropy

~/anaconda3/envs/paddle/lib/python3.7/site-packages/deepmatch/models/youtubednn.py in YoutubeDNN(user_feature_columns, item_feature_columns, num_sampled, user_dnn_hidden_units, dnn_activation, dnn_use_bn, l2_reg_dnn, l2_reg_embedding, dnn_dropout, output_activation, seed)
     74     model.__setattr__("item_input", item_inputs_list)
     75     model.__setattr__("item_embedding",
---> 76                       get_item_embedding(pooling_item_embedding_weight, item_features[item_feature_name]))
     77 
     78     return model

~/anaconda3/envs/paddle/lib/python3.7/site-packages/deepmatch/utils.py in get_item_embedding(item_embedding, item_input_layer)
     34 def get_item_embedding(item_embedding, item_input_layer):
     35     return Lambda(lambda x: tf.squeeze(tf.gather(item_embedding, x), axis=1))(
---> 36         item_input_layer)
     37 
     38 

~/anaconda3/envs/paddle/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, *args, **kwargs)
    982     if _in_functional_construction_mode(self, inputs, args, kwargs, input_list):
    983       return self._functional_construction_call(inputs, args, kwargs,
--> 984                                                 input_list)
    985 
    986     # Maintains info about the `Layer.call` stack.

~/anaconda3/envs/paddle/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py in _functional_construction_call(self, inputs, args, kwargs, input_list)
   1120       # Check input assumptions set after layer building, e.g. input shape.
   1121       outputs = self._keras_tensor_symbolic_call(
-> 1122           inputs, input_masks, args, kwargs)
   1123 
   1124       if outputs is None:

~/anaconda3/envs/paddle/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py in _keras_tensor_symbolic_call(self, inputs, input_masks, args, kwargs)
    852       return nest.map_structure(keras_tensor.KerasTensor, output_signature)
    853     else:
--> 854       return self._infer_output_signature(inputs, args, kwargs, input_masks)
    855 
    856   def _infer_output_signature(self, inputs, args, kwargs, input_masks):

~/anaconda3/envs/paddle/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py in _infer_output_signature(self, inputs, args, kwargs, input_masks)
    898                               build_graph=False)
    899       outputs = nest.map_structure(
--> 900           keras_tensor.keras_tensor_from_tensor, outputs)
    901 
    902     if hasattr(self, '_set_inputs') and not self.inputs:

~/anaconda3/envs/paddle/lib/python3.7/site-packages/tensorflow/python/util/nest.py in map_structure(func, *structure, **kwargs)
    912 
    913   return pack_sequence_as(
--> 914       structure[0], [func(*x) for x in entries],
    915       expand_composites=expand_composites)
    916 

~/anaconda3/envs/paddle/lib/python3.7/site-packages/tensorflow/python/util/nest.py in <listcomp>(.0)
    912 
    913   return pack_sequence_as(
--> 914       structure[0], [func(*x) for x in entries],
    915       expand_composites=expand_composites)
    916 

~/anaconda3/envs/paddle/lib/python3.7/site-packages/tensorflow/python/keras/engine/keras_tensor.py in keras_tensor_from_tensor(tensor)
    592       break
    593 
--> 594   out = keras_tensor_cls.from_tensor(tensor)
    595 
    596   if hasattr(tensor, '_keras_mask'):

~/anaconda3/envs/paddle/lib/python3.7/site-packages/tensorflow/python/keras/engine/keras_tensor.py in from_tensor(cls, tensor)
    180       # Fallback to the generic arbitrary-typespec KerasTensor
    181       name = getattr(tensor, 'name', None)
--> 182       type_spec = type_spec_module.type_spec_from_value(tensor)
    183       return cls(type_spec, name=name)
    184 

~/anaconda3/envs/paddle/lib/python3.7/site-packages/tensorflow/python/framework/type_spec.py in type_spec_from_value(value)
    888         3, "Failed to convert %r to tensor: %s" % (type(value).__name__, e))
    889 
--> 890   raise TypeError(f"Could not build a TypeSpec for {value} of "
    891                   f"unsupported type {type(value)}.")
    892 

TypeError: Could not build a TypeSpec for KerasTensor(type_spec=TensorSpec(shape=(None, 16), dtype=tf.float32, name=None), name='tf.compat.v1.squeeze/Squeeze:0', description="created by layer 'tf.compat.v1.squeeze'") of unsupported type <class 'tensorflow.python.keras.engine.keras_tensor.KerasTensor'>

Operating environment(运行环境):

python version 3.7
tensorflow version 2.8
deepmatch version 0.2.0
OS:Ubuntu 18.4
CPU: x86_64

**Comment by LXlearning** [comment]
才发现是一样的问题，白折腾一下午了，应该是不支持tf2.x版本吧

**Comment by shenweichen** [comment]
升级一下最新版本，然后用tf2.5试试
