### ISSUE TITLE
in batch 负采样

### ISSUE THREAD

**Issue by yexiao1107** [shenweichen/DeepMatch#73]
Please refer to the [FAQ](https://deepmatch.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepMatch/issues) before you ask the question.

**Describe the question(问题描述)**
A clear and concise description of what the question is.
大佬，不知道dssm对于in batch 负采样如何实现，我自己在训练数据时候发现如果随机负采样，user embedding没有区分度，但是item embedding是有区分度的，查阅资料有同学说可能是将item的冷热做了区分，并没有学习到user的兴趣，请问对于双塔模型这块
有什么调优的经验吗
**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.4.0,]
 - deepmatch version [e.g. 0.2.0,]

**Comment by johndkl** [comment]
我也是这样， user 没有区分度，而且我还用了热门打压。 代码里的run_dssm_negsampling.py不是in batch 负采样吗

**Comment by johndkl** [comment]
https://zhuanlan.zhihu.com/p/358544636
实测有效

**Comment by guixianjin** [comment]
in-batach 负采样 还可以参考：https://zhuanlan.zhihu.com/p/336509201 或者 https://zhuanlan.zhihu.com/p/518561076

**Comment by shenweichen** [comment]
deepmatch v0.3.0版本开始已经支持了inbatch负采样，使用方法可参考 https://github.com/shenweichen/DeepMatch/blob/master/examples/colab_MovieLen1M_DSSM_InBatchSoftmax.ipynb
