### ISSUE TITLE
comirec还有LabelAwareAttention？我看论文是直接argmax

### ISSUE THREAD

**Issue by chenkkkk** [shenweichen/DeepMatch#92]
https://github.com/shenweichen/DeepMatch/blob/93ca4371386223e2ae0b396b8860f363bd6abf67/deepmatch/models/comirec.py#L173

**Comment by chenkkkk** [comment]
@liyuan97

**Comment by shenweichen** [comment]
argmax是label aware的一种特殊形式，我们在代码里做了兼容支持多种模式，可以看下相关的实现@chenkkkk

**Comment by RyanLee-Dev** [comment]
是吗 我明天确认一下

**Comment by chenkkkk** [comment]
ok
